### ISSUE TITLE
Project Plan: Conversation Access Control

### ISSUE THREAD

**Issue by nvaa36** [lysanderp41/CodeUSummer2017#70]
Order:
- [x] 1. Create AccessLevel enum in client/common #60 
- [x] 2. Create UserAccessLevel class #69 
- [x] 3. Create a store for UserAccessLevels #68
- [x] 4. Make UserAccess functions in ConversationContext #58 
- [x] 4. Modify Persistence for `C-ADD` #67 
- [x] 4. Edit c-add to take in a defaultAccessLevel #66 
- [x] 4. Edit 'info' to display UserAccessLevel #65 
- [x] 4. Edit m-list to fail or succeed #64 
- [x] 4. Edit m-add to fail or succeed #63 
- [x] 4. Edit c-join to set UserAccessLevel #62 

Don't have default issue on here because I'm not sure where it goes.
